server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          preLogger: true
          postLogger: true
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
        - id: shop-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/shop/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server.luckytree-zwsm.svc.cluster.local:8761/eureka

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
